import {
  Entity,
  Column,
  ManyToOne,
  JoinColumn,
  Index,
  BeforeInsert,
  BeforeUpdate,
} from 'typeorm';
import { BaseEntity } from '../../shared/entities/base.entity';
import { User } from '../../auth/entities/user.entity';

export enum TemplateStatus {
  DRAFT = 'draft',
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  DISABLED = 'disabled',
}

export enum TemplateCategory {
  MARKETING = 'MARKETING',
  UTILITY = 'UTILITY',
  AUTHENTICATION = 'AUTHENTICATION',
}

export enum TemplateLanguage {
  ES = 'es',
  EN = 'en',
  PT = 'pt',
}

/**
 * Normaliza el nombre al formato exigido por WhatsApp:
 * - trim + lowercase
 * - sin tildes/acentos
 * - sin símbolos raros
 * - espacios -> _
 *
 * Ej: "Recordatorio Cita ¡Urgente!" -> "recordatorio_cita_urgente"
 */
function normalizeTemplateName(name: string) {
  return (name ?? '')
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^\w\s]/g, '')
    .replace(/\s+/g, '_');
}

@Entity('templates')
@Index(['name', 'language', 'userId'], { unique: true })
@Index(['status', 'userId'])
export class Template extends BaseEntity {
  @Column({ length: 100 })
  name: string;

  @Column({
    type: 'enum',
    enum: TemplateCategory,
    default: TemplateCategory.UTILITY,
  })
  category: TemplateCategory;

  @Column({
    type: 'enum',
    enum: TemplateLanguage,
    default: TemplateLanguage.ES,
  })
  language: TemplateLanguage;

  @Column({
    type: 'enum',
    enum: TemplateStatus,
    default: TemplateStatus.DRAFT,
  })
  status: TemplateStatus;

  /**
   * Cuerpo principal del template (el BODY de la plantilla de WhatsApp).
   * Ej: "Hola {{1}}, tu cita es a las {{2}}."
   */
  @Column({ type: 'text' })
  body: string;

  /**
   * Header opcional: texto fijo o media (imagen/documento/video).
   * Lo dejamos como jsonb para flexibilidad.
   */
  @Column({ type: 'jsonb', nullable: true })
  header: {
    type: 'TEXT' | 'MEDIA';
    text?: string;
    mediaUrl?: string;
    mediaType?: 'IMAGE' | 'VIDEO' | 'DOCUMENT';
  } | null;

  /**
   * Footer opcional de la plantilla ("Gracias", "No responder a este mensaje", etc.)
   */
  @Column({ type: 'jsonb', nullable: true })
  footer:
    | {
      text: string;
    }
    | null;

  /**
   * Botones interactivos aprobados por Meta.
   * QUICK_REPLY, URL, PHONE_NUMBER
   */
  @Column({ type: 'jsonb', nullable: true })
  buttons:
    | Array<{
      type: 'QUICK_REPLY' | 'URL' | 'PHONE_NUMBER';
      text: string;
      url?: string;
      phoneNumber?: string;
    }>
    | null;

  /**
   * Parámetros declarados como variables {{1}}, {{2}}, etc.
   * Esto es útil para metadata interna (no se manda tal cual a WhatsApp).
   */
  @Column({ type: 'jsonb', nullable: true })
  parameters:
    | Array<{
      name: string;
      type: 'TEXT' | 'CURRENCY' | 'DATE_TIME';
      example: string;
    }>
    | null;

  /**
   * ID/handle que devuelve WhatsApp Business al aprobar la plantilla.
   * (En algunos flujos lo llaman 'id' o 'name' remoto; aquí guardamos el que necesites).
   *
   * OJO: MessagesService actualmente envía usando .name, no este campo,
   * pero lo dejamos porque igual es útil para auditar.
   */
  @Column({ length: 100, nullable: true })
  whatsappTemplateId: string | null;

  /**
   * Si Meta rechaza la plantilla, guardamos el motivo acá.
   */
  @Column({ type: 'jsonb', nullable: true })
  rejectionReason:
    | {
      code: string;
      message: string;
      details?: string;
    }
    | null;

  /**
   * Timestamps de estado de aprobación con Meta.
   */
  @Column({ type: 'timestamp', nullable: true })
  submittedAt: Date | null;

  @Column({ type: 'timestamp', nullable: true })
  approvedAt: Date | null;

  @Column({ type: 'timestamp', nullable: true })
  rejectedAt: Date | null;

  /**
   * Cuántas veces se ha usado en envíos reales.
   */
  @Column({ type: 'int', default: 0 })
  usageCount: number;

  /**
   * Activa / apagada en nuestro sistema.
   * Ojo: si la desactivas, en TemplatesService.update()
   * pasamos el estado a DISABLED.
   */
  @Column({ type: 'boolean', default: true })
  active: boolean;

  /**
   * Metadata libre (por ejemplo: `{ createdFrom: 'UI', autoGenerated: true }`).
   */
  @Column({ type: 'jsonb', nullable: true })
  metadata: Record<string, any> | null;

  /**
   * Dueño / tenant.
   */
  @ManyToOne(() => User, user => user.templates)
  @JoinColumn({ name: 'userId' })
  user: User;

  @Column()
  userId: string;

  /**
   * Getter de conveniencia.
   * MessagesService llama a template.isApproved para saber si puede enviar.
   */
  get isApproved(): boolean {
    return this.status === TemplateStatus.APPROVED;
  }

  /**
   * Cuántos parámetros dinámicos tiene esta plantilla.
   */
  get parameterCount(): number {
    return this.parameters?.length || 0;
  }

  /**
   * Hook: antes de guardar o actualizar, forzamos el formato oficial de nombre.
   * Esto asegura que el índice único (name+language+userId) compare valores ya normalizados.
   */
  @BeforeInsert()
  @BeforeUpdate()
  normalizeNameHook() {
    if (this.name) {
      this.name = normalizeTemplateName(this.name);
    }
  }
}
